Update

diff --git a/TableMenu b/TableMenu
--- a/TableMenu
+++ b/TableMenu
@@ -310,7 +310,7 @@ do
             ;;
         
         "Select From Table")
-            selectFromTable "$tableName"
+            SelectFromTableByID "$tableName"
             ;;
         
         "Delete From Table")
@@ -333,3 +333,25 @@ do
     esac
 done
 }
+function SelectFromTableByID()
+{
+    parentDir="Databases"
+    database="db2"
+    fullPath="$parentDir/$database"
+    tableName=$1
+    cd "$fullPath" || { echo -e "${RED}Error: Failed to change directory to $fullPath${RESET}"; return 1; }
+
+
+    read -p "Enter ID: " id
+    while [[ -z "$id" || ! "$id" =~ ^[0-9]+$ ]]; do
+        echo -e "${RED}Error: ID must be an integer${RESET}"
+        read -p "Enter ID: " id
+    done
+    if ! grep -q "^$id," "$tableName"; then
+    	echo -e "${YELLOW}Record with ID $id not found.${RESET}"
+    	return 1	
+    fi
+    
+   awk -F"," -v id="$id" '$1 == id {print}' "$tableName"
+}
+
